const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let metrics={};
let csrfToken=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg,type=''){const t=document.createElement('div');t.className='toast-item '+type;t.textContent=msg;$('#toast').appendChild(t);setTimeout(()=>t.remove(),3200)}
function setAuth(show){$('#loginView').classList.toggle('hidden',!show);$('#appView').classList.toggle('hidden',show)}
async function ensureCsrf(){if(csrfToken)return csrfToken;const r=await fetch('/api/csrf');const d=await r.json();csrfToken=d.token;return csrfToken}
async function api(url,opt={}){opt={...opt};const method=(opt.method||'GET').toUpperCase();const headers={'Content-Type':'application/json',...(opt.headers||{})};if(method!=='GET'&&method!=='HEAD'){headers['X-CSRF-Token']=await ensureCsrf()}opt.headers=headers;const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function checkAuth(){
  try{
    await ensureCsrf();
    const status = window.__threatLensBootstrapState || await api('/api/auth/status');
    setAuth(true);
    // Bootstrap state is authoritative: do not call /me first on a fresh workspace.
    // This also prevents a stale session/API error from hiding the first-run setup.
    if(status && status.setup_available === true){
      showSetupMode();
      return;
    }
    const d=await api('/api/auth/me');
    if(d.authenticated){
      setAuth(false); fillUser(d.user); await loadAll(); initialRoute();
    }else{
      showLoginMode();
    }
  }catch(err){
    setAuth(true);
    // Keep the normal sign-in screen only when the status endpoint cannot be read.
    showLoginMode();
  }
}
function fillUser(u){window.currentUser=u;$('#profileName').textContent=u.name;$('#profileRole').textContent=u.role;$('#helloName').textContent=u.name.split(' ')[0];$('#avatar').textContent=u.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();$$('[data-page=users],[data-page=security]').forEach(el=>el.style.display=u.role==='Administrator'?'flex':'none')}
$('#togglePassword').onclick=()=>{const x=$('#loginPassword');x.type=x.type==='password'?'text':'password'};
const DEMO_ACCOUNTS={admin:{email:'admin@threatlens.ai',password:'ThreatLens!2026_Admin'},analyst:{email:'analyst@threatlens.ai',password:'ThreatLens!2026_Analyst'}};
$$('[data-demo]').forEach(b=>b.onclick=()=>{const a=DEMO_ACCOUNTS[b.dataset.demo];$('#loginEmail').value=a.email;$('#loginPassword').value=a.password;$('#loginError').textContent='';$('#loginEmail').focus();toast(`${b.dataset.demo==='admin'?'Administrator':'Analyst'} demo credentials loaded`,'good')});
$('#forgot').onclick=e=>{e.preventDefault();openModal(`<div class="modal-kicker">ACCOUNT RECOVERY</div><h2>Forgot password?</h2><p class="modal-subtitle">For this local SOC prototype, password recovery is handled by an administrator rather than by exposing a reset link.</p><div class="account-status"><span class="dot blue"></span><div><b>Administrator recovery</b><small>Ask an administrator to unlock the account or issue a temporary password. The action is recorded in the security audit trail.</small></div></div><div class="modal-actions"><button class="primary" id="forgotClose">Close</button></div>`);$('#forgotClose').onclick=closeModal};
function showLoginMode(){
  $('#authTitle').textContent='Sign in'; $('#authSubtitle').textContent='Access your security operations workspace.';
  $('#loginForm').classList.remove('hidden'); $('#setupPanel').classList.add('hidden'); $('#loginExtras').classList.remove('hidden');
}
function showSetupMode(){
  $('#authTitle').textContent='Set up your workspace'; $('#authSubtitle').textContent='Create the first administrator for this ThreatLens security workspace.';
  $('#loginForm').classList.add('hidden'); $('#setupPanel').classList.remove('hidden'); $('#loginExtras').classList.add('hidden');
}
$('#setupForm').onsubmit=async e=>{e.preventDefault();$('#setupError').textContent='';if($('#setupPassword').value!==$('#setupConfirm').value){$('#setupError').textContent='Passwords do not match.';return}try{const d=await api('/api/auth/initialize',{method:'POST',body:JSON.stringify({name:$('#setupName').value,email:$('#setupEmail').value,password:$('#setupPassword').value})});csrfToken=d.csrf||csrfToken;fillUser(d.user);setAuth(false);await loadAll();toast('Security workspace initialized','good')}catch(err){$('#setupError').textContent=err.message}};
$('#loadDemoBtn').onclick=async()=>{if(!confirm('Load the documented hackathon Administrator and Analyst demo accounts? This is available only on a fresh workspace.'))return;try{await api('/api/auth/load-demo',{method:'POST'});showLoginMode();toast('Hackathon demo accounts loaded','good')}catch(err){$('#setupError').textContent=err.message}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});csrfToken=d.csrf||csrfToken;fillUser(d.user);setAuth(false);await loadAll()}catch(err){$('#loginError').textContent=err.message}};
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});setAuth(true);toast('Signed out','good')};
function navigate(page){
  const target=document.getElementById('page-'+page);
  if(!target)return;
  // Make navigation deterministic: hide every page, then show exactly one.
  $$('.page').forEach(section=>{
    section.classList.toggle('active',section===target);
    section.style.display=section===target?'block':'none';
  });
  $$('.nav').forEach(button=>button.classList.toggle('active',button.dataset.page===page));
  history.replaceState(null,'','#'+page);
  if(page==='incidents')loadIncidents();
  if(page==='history')loadHistory();
  if(page==='users')loadUsers();
  if(page==='security')loadSecurityAudit();
  if(page==='analytics')renderAnalytics();
  if(page==='home')loadDashboard();
  if(page==='settings')loadSettings();
}
// Use document-level delegation so every navigation item works, including the
// Administration navigation and buttons rendered outside the primary nav.
document.addEventListener('click',e=>{
  const navButton=e.target.closest('[data-page]');
  if(navButton){e.preventDefault();navigate(navButton.dataset.page);return;}
  const gotoButton=e.target.closest('[data-goto]');
  if(gotoButton){e.preventDefault();navigate(gotoButton.dataset.goto);}
});
function initialRoute(){
  const requested=location.hash.replace('#','');
  const allowed=['home','incidents','scanner','intel','analytics','history','users','security','settings'];
  navigate(allowed.includes(requested)?requested:'home');
}
async function loadAll(){try{metrics=await api('/api/metrics');const h=await api('/api/health');$('#sideModel').textContent=h.trained?'Model bundle ready':'Model bundle missing';$('#postModel').textContent=h.trained?'Exported ML bundle':'Run Colab export';$('#scannerModel').textContent=metrics.best_model||'Random Forest';renderAnalytics();await loadDashboard()}catch(e){toast(e.message,'bad')}}
async function loadDashboard(){try{const d=await api('/api/dashboard');const ds=d.dataset||{};$('#mThreats').textContent=d.scan_stats.phishing;$('#mScans').textContent=d.scan_stats.total;$('#mIncidents').textContent=d.scan_stats.open_incidents;const bm=d.best_model||'—', ba=(d.models?.[bm]?.accuracy);$('#mAccuracy').textContent=ba!=null?ba+'%':'—';$('#mModel').textContent=bm;$('#incidentCount').textContent=d.scan_stats.open_incidents;$('#postDataset').textContent=ds.instances?Number(ds.instances).toLocaleString()+' URLs':'UCI PhiUSIIL';renderChart(d.recent||[]);renderRecent(d.recent||[])}catch(e){toast(e.message,'bad')}}
function renderChart(rows){const w=700,h=190,p=25;let safe=rows.filter(x=>x.verdict==='SAFE').length,ph=rows.filter(x=>x.verdict==='PHISHING').length;const vals=[safe,ph,Math.max(0,rows.length-safe-ph)];const max=Math.max(...vals,1);const bars=vals.map((v,i)=>{const x=100+i*180;const bh=(v/max)*110;return `<rect x="${x}" y="${140-bh}" width="72" height="${bh}" rx="5" fill="${i===1?'#dc2626':'#2563eb'}" opacity="${i===2?.25:1}"/><text x="${x+36}" y="165" text-anchor="middle" font-size="10" fill="#667085">${['SAFE','PHISHING','OTHER'][i]}</text><text x="${x+36}" y="${130-bh}" text-anchor="middle" font-size="11" font-weight="700" fill="#344054">${v}</text>`}).join('');$('#activityChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="30" y1="140" x2="670" y2="140" stroke="#e4e8ef"/>${bars}</svg>`}
function renderRecent(rows){if(!rows.length){$('#recentIncidents').innerHTML='<div class="empty">No scans yet. Run your first URL analysis.</div>';return}const ph=rows.filter(r=>r.verdict==='PHISHING').slice(0,5);$('#recentIncidents').innerHTML=tableHtml(ph.length?ph:rows.slice(0,5),true)}
function tableHtml(rows,incident=false){return `<table class="table"><thead><tr><th>${incident?'SEVERITY':'URL'}</th><th>URL</th><th>VERDICT</th><th>RISK</th><th>TIME</th></tr></thead><tbody>${rows.map(r=>{const sev=r.risk>=85?'CRITICAL':r.risk>=65?'HIGH':'MEDIUM';return `<tr><td>${incident?`<span class="status ${r.risk>=65?'red':'amber'}">${sev}</span>`:esc(r.model||'')}</td><td class="url-cell" title="${esc(r.url)}">${esc(r.url)}</td><td><span class="status ${r.verdict==='PHISHING'?'red':'green'}">${r.verdict}</span></td><td>${Number(r.risk).toFixed(1)}%</td><td>${esc(r.created_at||'')}</td></tr>`}).join('')}</tbody></table>`}
async function scan(url){if(!url)return toast('Enter a URL first','bad');try{const d=await api('/api/predict',{method:'POST',body:JSON.stringify({url})});renderResult(d);toast(`${d.prediction} · risk ${d.risk}%`,d.is_phishing?'bad':'good');loadDashboard()}catch(e){toast(e.message,'bad')}}
$('#scanBtn').onclick=()=>scan($('#scanInput').value);$$('[data-scan]').forEach(b=>b.onclick=()=>{$('#scanInput').value=b.dataset.scan;scan(b.dataset.scan)});
function renderResult(d){const f=d.features;const risk=d.risk;const items=[['HTTPS',f.https?'Secure':'Not using HTTPS',!f.https],['IP address',f.ip?'Detected':'Not detected',f.ip],['@ symbol',f.has_at?'Detected':'Not detected',f.has_at],['Shortener',f.shortener?'Detected':'Not detected',f.shortener],['Suspicious keywords',`${f.keyword_count} detected`,f.keyword_count>0],['URL length',`${f.length} characters`,f.length>100],['Double slash',f.double_slash?'Detected':'Not detected',f.double_slash],['Digits',`${f.digit_count} in URL`,f.digit_count>=5]];$('#result').classList.remove('hidden');$('#result').innerHTML=`<div class="result-card"><div class="result-top"><div class="verdict-big"><div class="risk-ring" style="--risk:${risk*3.6}deg"><div><b>${Math.round(risk)}</b><small>RISK / 100</small></div></div><span class="status ${d.is_phishing?'red':'green'}" style="margin-top:14px">${d.prediction}</span></div><div class="result-detail"><span class="eyebrow">THREAT ASSESSMENT · ${esc(d.model)}</span><h2>${d.is_phishing?'Phishing URL detected':'No phishing signal detected'}</h2><div class="result-url">${esc(f.url)}</div><div class="confidence"><div><span>MODEL CONFIDENCE</span><b>${d.confidence}%</b></div><div class="progress"><i style="width:${d.confidence}%"></i></div></div><p style="font-size:11px;color:#667085;margin-top:14px">The risk score is the model's phishing probability. Confidence is the probability of the predicted class.</p></div></div><div class="indicator-grid">${items.map(x=>`<div class="indicator ${x[2]?(d.is_phishing?'bad':'warn'):''}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div><div class="panel-head" style="margin-top:20px;padding-left:0;padding-right:0"><div><b>URL profile</b><small>Exact features extracted before inference</small></div><span class="pill">MODEL INPUT</span></div><div class="profile-grid">${[['Host',f.host],['URL length',f.length],['Dots',f.dots],['Subdomains',f.subdomain_depth],['Query length',f.query_length],['Digit count',f.digit_count]].map(x=>`<div class="profile-item"><small>${x[0]}</small><b>${esc(x[1])}</b></div>`).join('')}</div></div>`;$('#result').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadIncidents(){try{const d=await api('/api/incidents');$('#incidentsTable').innerHTML=d.incidents.length?tableHtml(d.incidents,true):'<div class="empty">No phishing incidents generated yet.</div>'}catch(e){toast(e.message,'bad')}}
async function loadHistory(){try{const d=await api('/api/history');$('#historyTable').innerHTML=d.scans.length?tableHtml(d.scans,false):'<div class="empty">No scans in your history.</div>'}catch(e){toast(e.message,'bad')}}
$('#clearHistory').onclick=async()=>{if(confirm('Clear your scan history?')){await api('/api/history',{method:'DELETE'});loadHistory();loadDashboard();toast('History cleared','good')}};
function renderAnalytics(){const models=metrics.models||{};const names=Object.keys(models);$('#analyticsCards').innerHTML=names.map(n=>{const m=models[n];return `<div class="analytics-card"><div class="model-title">${esc(n)}</div><div class="big">${m.accuracy}%</div><small>Accuracy</small><div class="metric-row"><span>Precision</span><b>${m.precision}%</b></div><div class="metric-row"><span>Recall</span><b>${m.recall}%</b></div><div class="metric-row"><span>F1 Score</span><b>${m.f1}%</b></div></div>`}).join('');$('#analyticsMatrices').innerHTML=names.map(n=>matrixHtml(n,models[n].confusion_matrix)).join('')}
function matrixHtml(name,cm){const a=cm?.[0]?.[0]??0,b=cm?.[0]?.[1]??0,c=cm?.[1]?.[0]??0,d=cm?.[1]?.[1]??0;return `<div class="panel matrix"><div class="panel-head" style="padding:0 0 12px;border:0"><div><b>${esc(name)}</b><small>Confusion matrix · actual vs predicted</small></div></div><div class="matrix-grid"><div class="axis"></div><div class="axis">SAFE</div><div class="axis">PHISH</div><div class="axis">SAFE</div><div class="cell">${a.toLocaleString()}</div><div class="cell">${b.toLocaleString()}</div><div class="axis">PHISH</div><div class="cell">${c.toLocaleString()}</div><div class="cell hot">${d.toLocaleString()}</div></div><div class="matrix-legend">Rows = actual class · columns = predicted class · 0 = SAFE, 1 = PHISHING</div></div>`}
async function loadUsers(){try{const d=await api('/api/users');const users=d.users||[];$('#userTotal').textContent=users.length;$('#adminTotal').textContent=users.filter(u=>u.role==='Administrator').length;$('#analystTotal').textContent=users.filter(u=>u.role==='Analyst').length;$('#usersTable').innerHTML=users.length?`<table class="table"><thead><tr><th>USER</th><th>ROLE</th><th>STATUS</th><th>LAST LOGIN</th><th>SECURITY</th><th>ACTIONS</th></tr></thead><tbody>${users.map(u=>{const locked=u.locked_until&&Number(u.locked_until)*1000>Date.now();return `<tr><td><b>${esc(u.name)}</b><small style="display:block;color:#667085">${esc(u.email)}</small></td><td><span class="pill">${esc(u.role)}</span></td><td><span class="status ${u.status==='Active'?'green':'red'}">${esc(u.status)}${locked?' · LOCKED':''}</span></td><td>${esc(u.last_login_at||'Never')}</td><td>${locked?`<span class="status red">${u.failed_attempts} failures</span>`:'<span class="status green">OK</span>'}</td><td><button class="table-action" data-admin-action="manage" data-user-id="${u.id}">Manage</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">No workspace users found.</div>'}catch(e){toast(e.message,'bad')}}
async function adminUserAction(id, action){let body={};if(action==='unlock')body.unlock=true;if(action==='disable')body.status='Disabled';if(action==='enable')body.status='Active';if(action==='revoke')body.revoke_sessions=true;if(action==='role')body.role=prompt('Enter role: Analyst or Administrator','Analyst');if(action==='reset'){const p=prompt('Enter a temporary password (minimum 12 characters):','ThreatLensTemp@2026');if(!p)return;body.password=p;try{await api(`/api/users/${id}/reset-password`,{method:'POST',body:JSON.stringify(body)});toast('Password reset; active sessions revoked','good');loadUsers();return}catch(e){toast(e.message,'bad');return}}else{try{await api(`/api/users/${id}`,{method:'PATCH',body:JSON.stringify(body)});toast('User security settings updated','good');loadUsers();if(location.hash==='#security')loadSecurityAudit()}catch(e){toast(e.message,'bad')}}}
async function openUserManager(id){const d=await api('/api/users');const u=d.users.find(x=>x.id==id);if(!u)return;const locked=u.locked_until&&Number(u.locked_until)*1000>Date.now();openModal(`<div class="modal-kicker">ADMINISTRATOR CONTROL</div><h2>Manage user</h2><p class="modal-subtitle">Administrators can resolve access and session-security issues without viewing user passwords.</p><div class="profile-details"><div><small>USER</small><b>${esc(u.name)}</b></div><div><small>EMAIL</small><b>${esc(u.email)}</b></div><div><small>ROLE</small><b>${esc(u.role)}</b></div><div><small>STATUS</small><b>${esc(u.status)}${locked?' · Locked':''}</b></div></div><div class="security-actions"><button class="secondary" id="unlockUser">Unlock account</button><button class="secondary" id="resetUser">Reset password</button><button class="secondary" id="revokeUser">Revoke sessions</button><button class="secondary" id="roleUser">Change role</button><button class="secondary" id="toggleUser">${u.status==='Active'?'Disable account':'Enable account'}</button></div><div class="modal-actions"><button class="primary" id="closeUser">Done</button></div>`);$('#closeUser').onclick=closeModal;$('#unlockUser').onclick=()=>adminUserAction(id,'unlock');$('#resetUser').onclick=()=>adminUserAction(id,'reset');$('#revokeUser').onclick=()=>adminUserAction(id,'revoke');$('#roleUser').onclick=()=>adminUserAction(id,'role');$('#toggleUser').onclick=()=>adminUserAction(id,u.status==='Active'?'disable':'enable')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-admin-action="manage"]');if(b)openUserManager(Number(b.dataset.userId))});
async function loadSecurityAudit(){try{const d=await api('/api/audit');const events=d.events||[];$('#auditTable').innerHTML=events.length?`<table class="table"><thead><tr><th>TIME</th><th>EVENT</th><th>ACTOR</th><th>TARGET</th><th>DETAIL</th><th>IP</th></tr></thead><tbody>${events.map(x=>`<tr><td>${esc(x.created_at)}</td><td><span class="pill">${esc(x.event)}</span></td><td>${esc(x.actor||'System')}</td><td>${esc(x.target||'—')}</td><td>${esc(x.detail||'')}</td><td>${esc(x.ip||'local')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No security events recorded yet.</div>'}catch(e){toast(e.message,'bad')}}
function openModal(html){$('#modalContent').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){$('#modalBackdrop').classList.add('hidden');$('#modalContent').innerHTML=''}
$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};
function openChangePassword(){openModal(`<div class="modal-kicker">ACCOUNT SECURITY</div><h2>Change password</h2><p class="modal-subtitle">Your current password is required. Changing it revokes the current session.</p><form id="changePasswordForm" class="modal-form"><label>Current password<input id="currentPassword" type="password" required></label><label>New password<input id="newPassword" type="password" minlength="12" required placeholder="Minimum 12 characters"></label><label>Confirm new password<input id="confirmPassword" type="password" minlength="12" required></label><div class="auth-error" id="changePasswordError"></div><div class="modal-actions"><button type="button" class="secondary" id="cancelPassword">Cancel</button><button type="submit" class="primary">Change password</button></div></form>`);$('#cancelPassword').onclick=closeModal;$('#changePasswordForm').onsubmit=async e=>{e.preventDefault();if($('#newPassword').value!==$('#confirmPassword').value){$('#changePasswordError').textContent='New passwords do not match.';return}try{await api('/api/auth/change-password',{method:'POST',body:JSON.stringify({current_password:$('#currentPassword').value,new_password:$('#newPassword').value})});closeModal();setAuth(true);toast('Password changed. Please sign in again.','good')}catch(err){$('#changePasswordError').textContent=err.message}}}
function openProfile(){const u=window.currentUser||{};openModal(`<div class="modal-kicker">IDENTITY & ACCESS</div><h2>My profile</h2><p class="modal-subtitle">Your authenticated ThreatLens workspace identity.</p><div class="profile-large"><span class="avatar large">${esc($('#avatar').textContent)}</span><div><b>${esc(u.name||'Analyst')}</b><small>${esc(u.role||'Analyst')}</small></div></div><div class="profile-details"><div><small>EMAIL</small><b>${esc(u.email||'')}</b></div><div><small>ROLE</small><b>${esc(u.role||'')}</b></div><div><small>WORKSPACE</small><b>ThreatLens Security Operations Center</b></div></div><div class="modal-actions"><button class="secondary" id="profilePasswordBtn">Change password</button><button class="secondary" id="profileSettingsBtn">Account settings</button><button class="primary" id="profileDoneBtn">Done</button></div>`);$('#profileDoneBtn').onclick=closeModal;$('#profilePasswordBtn').onclick=()=>{closeModal();openChangePassword()};$('#profileSettingsBtn').onclick=()=>{closeModal();navigate('settings')}}
function openAccount(){const u=window.currentUser||{};openModal(`<div class="modal-kicker">ACCOUNT</div><h2>Account security</h2><p class="modal-subtitle">Local prototype account controls.</p><div class="account-status"><span class="dot green"></span><div><b>Session protected</b><small>Authenticated through the local Flask session.</small></div></div><div class="account-status"><span class="dot green"></span><div><b>${esc(u.role||'Analyst')} role</b><small>${esc(u.email||'')}</small></div></div><div class="modal-actions"><button class="secondary" id="changePasswordBtn">Change password</button><button class="secondary" id="accountSettingsBtn">Open settings</button><button class="primary" id="accountCloseBtn">Close</button></div>`);$('#accountCloseBtn').onclick=closeModal;$('#changePasswordBtn').onclick=()=>{closeModal();openChangePassword()};$('#accountSettingsBtn').onclick=()=>{closeModal();navigate('settings')}}
function loadSettings(){const d=JSON.parse(localStorage.getItem('threatlensSettings')||'{}');if(d.workspaceName)$('#workspaceName').value=d.workspaceName;if(d.workspaceEnv)$('#workspaceEnv').value=d.workspaceEnv;if(d.timezone)$('#timezone').value=d.timezone;if(typeof d.notifications==='boolean')$('#notifyToggle').checked=d.notifications;if(typeof d.compact==='boolean')$('#compactToggle').checked=d.compact;$('#authToggle').checked=true;document.body.classList.toggle('compact-mode',!!d.compact)}
$('#saveSettingsBtn').onclick=()=>{const d={workspaceName:$('#workspaceName').value.trim()||'ThreatLens Security Operations Center',workspaceEnv:$('#workspaceEnv').value.trim()||'Local Hackathon Prototype',timezone:$('#timezone').value,notifications:$('#notifyToggle').checked,compact:$('#compactToggle').checked};localStorage.setItem('threatlensSettings',JSON.stringify(d));document.body.classList.toggle('compact-mode',d.compact);$('.tenant b').textContent=d.workspaceName.replace(' Security Operations Center','')||'Security Workspace';toast('Settings saved successfully','good')};
$('#addUserBtn').onclick=()=>openModal(`<div class="modal-kicker">IDENTITY & ACCESS</div><h2>Add workspace user</h2><p class="modal-subtitle">Create a local analyst or administrator account.</p><form id="addUserForm" class="modal-form"><label>Full name<input id="newUserName" required placeholder="Security Analyst"></label><label>Email<input id="newUserEmail" type="email" required placeholder="analyst@example.com"></label><label>Temporary password<input id="newUserPassword" type="password" minlength="12" required placeholder="Minimum 12 characters"></label><label>Role<select id="newUserRole"><option>Analyst</option><option>Administrator</option></select></label><div class="auth-error" id="addUserError"></div><div class="modal-actions"><button type="button" class="secondary" id="cancelAddUser">Cancel</button><button type="submit" class="primary">Create user</button></div></form>`);$('#cancelAddUser').onclick=closeModal;$('#addUserForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify({name:$('#newUserName').value,email:$('#newUserEmail').value,password:$('#newUserPassword').value,role:$('#newUserRole').value})});closeModal();await loadUsers();toast('User created successfully','good')}catch(err){$('#addUserError').textContent=err.message}};
$('#profile').onclick=e=>{if(e.target.closest('.profile-menu button'))return;$('#profileMenu').classList.toggle('hidden')};document.addEventListener('click',e=>{if(!e.target.closest('#profile'))$('#profileMenu')?.classList.add('hidden')});
document.addEventListener('click',async e=>{const a=e.target.closest('[data-profile-action]');if(!a)return;$('#profileMenu').classList.add('hidden');const action=a.dataset.profileAction;if(action==='profile')openProfile();if(action==='account')openAccount();if(action==='settings')navigate('settings');if(action==='logout'){$('#logout').click()}});
$('#notificationBtn').onclick=e=>{$('#notificationPanel').classList.toggle('hidden');$('#profileMenu').classList.add('hidden');$('#notificationBadge').textContent='0'};$('#clearNotifications').onclick=()=>{$('#notificationList').innerHTML='<div class="empty">No unread notifications.</div>';$('#notificationBadge').textContent='0'};
$('#helpBtn').onclick=()=>openModal(`<div class="modal-kicker">THREATLENS HELP</div><h2>Security Center help</h2><p class="modal-subtitle">Quick guide for the hackathon demonstration.</p><div class="help-list"><div><b>URL Scanner</b><span>Analyze a URL with the deployed Random Forest model.</span></div><div><b>Incidents & Alerts</b><span>Review phishing detections generated by scans.</span></div><div><b>ML Analytics</b><span>Compare the three trained models and confusion matrices.</span></div><div><b>Settings</b><span>Save workspace and analyst display preferences.</span></div></div><div class="modal-actions"><button class="primary" id="helpClose">Close</button></div>`);$('#helpClose').onclick=closeModal;
$('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase();if(q.length<3)return;const hit=(metrics?.models&&Object.keys(metrics.models).find(x=>x.toLowerCase().includes(q)));if(hit)navigate('analytics')};
setInterval(()=>{const d=new Date();const el=$('#clock');if(el)el.textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})},1000);
checkAuth();
$('#refreshAudit')?.addEventListener('click',loadSecurityAudit);
